model:
  vocab_size: 50257
  n_layers: 6
  n_heads: 8
  d_model: 512
  d_ff: 2048
  max_seq_len: 128
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 3e-4
  epochs: 10
  warmup_steps: 500
  weight_decay: 0.01
  grad_clip: 1.0
  checkpoint_dir: "./checkpoints"
  log_interval: 100

data:
  dataset_path: "./data/tinyshakespeare.txt"
  tokenizer: "custom"