model:
  vocab_size: 50257
  n_layers: 4
  n_heads: 4
  d_model: 256
  d_ff: 1024
  max_seq_len: 64
  dropout: 0.1

training:
  batch_size: 64
  learning_rate: 5e-4
  epochs: 5
  warmup_steps: 200
  weight_decay: 0.01
  grad_clip: 1.0
  checkpoint_dir: "./checkpoints_small"
  log_interval: 50

data:
  dataset_path: "./data/tinyshakespeare.txt"
  tokenizer: "custom"